# Generated by Django 5.2.3 on 2025-07-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_producto_id_producto_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='Stock',
        ),
    ]
