# Generated by Django 5.2.3 on 2025-07-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_rename_descripcion_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
